name: C/C++ CI

on:
  push:
    paths:     
    - 'c/**' 
  pull_request:
    paths:
    - 'c/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make test
      run: make test
    - name: make memcheck
      run: make memchek
    - name: make clean
      run: make clean
